steps:
  - name: gradle:7.5.1-jdk11
    id: static-analysis
    entrypoint: gradle
    args: [ 'sonar' ]
    secretEnv: [ 'SONAR_TOKEN' ]
    env:
      - 'sonar.login=$$SONAR_TOKEN'
  - name: gradle:7.5.1-jdk11
    id: unit-tests
    entrypoint: gradle
    args: [ 'test' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]
availableSecrets:
  secretManager:
    - versionName: projects/285597022882/secrets/SONAR_TOKEN/versions/1
      env: 'SONAR_TOKEN'
timeout: '1600s'
